# Generated by Django 2.0.3 on 2021-09-03 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='player_id',
        ),
    ]
