# Generated by Django 2.0.3 on 2021-09-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerAPI', '0002_auto_20210903_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='report_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='trustworthy',
            field=models.BooleanField(default=False),
        ),
    ]
