# Generated by Django 4.0.4 on 2022-04-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrustFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=50)),
                ('number_of_reports', models.CharField(max_length=50)),
                ('trust_factor', models.BooleanField()),
            ],
        ),
    ]
