# Generated by Django 4.0.4 on 2022-05-02 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trustfactor',
            old_name='number_of_reports',
            new_name='numberOfReports',
        ),
        migrations.RenameField(
            model_name='trustfactor',
            old_name='player_id',
            new_name='steamId',
        ),
        migrations.RenameField(
            model_name='trustfactor',
            old_name='trust_factor',
            new_name='trustFactor',
        ),
    ]
