# Generated by Django 4.0.4 on 2022-05-02 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_number_of_reports_trustfactor_numberofreports_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrustFactor',
            new_name='scumBag',
        ),
    ]
