# Generated by Django 4.0.4 on 2022-05-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_trustfactor_scumbag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scumbag',
            name='numberOfReports',
        ),
        migrations.RemoveField(
            model_name='scumbag',
            name='steamId',
        ),
        migrations.RemoveField(
            model_name='scumbag',
            name='trustFactor',
        ),
        migrations.AddField(
            model_name='scumbag',
            name='number_of_reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scumbag',
            name='steam_id',
            field=models.IntegerField(default=0),
        ),
    ]
