# Generated by Django 4.0.4 on 2022-05-29 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_scumbag_numberofreports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scumbag',
            name='steam_id',
            field=models.CharField(max_length=50),
        ),
    ]
